version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install -g yarn
      - ssh-keygen -F github.com || ssh-keyscan github.com >>~/.ssh/known_hosts
      - git config --global user.email "gotitmachine@got-it.ai"
      - git config --global user.name "GotIt Machine"
      - git clone https://github.com/${GITHUB_OWNER}/${GITHUB_REPO}.git /source
      - cd /source
      - git checkout -f "$CODEBUILD_RESOLVED_SOURCE_VERSION"
      - git submodule init
      - git submodule update --recursive
      - cd /source
      - yarn install
      - cd aha-react
      - yarn install
      - apt-get install jq
  build:
    commands:
      - cd /source
      - export VERSION=`jq -r .version package.json`
      - yarn build
  post_build:
    commands:
      - cd /source; bash infra/docs.deploy.sh
      
artifacts:
  files:
    - 'public/**/*'
