AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Aha Design System - Icons Lib
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Configurations"
        Parameters:
          - ApplicationName
          - GitHubOwner
          - GitHubRepo
          - GitHubBranch
          - ArtifactBucket
          - NPMTag

Parameters:
  ApplicationName:
    Description: This will be used to name the pipeline and build resources
    Type: String
    Default: aha-design-system-icons-lib
    AllowedPattern: '[A-Za-z0-9-]+'
  GitHubOwner:
    Type: String
    Default: gotitinc
    Description: GitHub repository owner
  GitHubRepo:
    Type: String
    Default: aha-icons
    Description: GitHub repository name
  GitHubBranch:
    Type: String
    Default: master
    Description: GitHub repository branch
  ArtifactBucket:
    Type: String
    Default: cf-templates-5bizf5p6pxoh-us-east-2
    AllowedValues:
      - cf-templates-5bizf5p6pxoh-us-east-2
    Description: Name of existing S3 bucket for storing pipeline artifacts
  NPMTag:
    Description: Tag for NPM release
    Type: String
    Default: latest

Resources:
  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      RoleName: !Sub ${ApplicationName}-CodeBuild-${AWS::Region}
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: "sts:AssumeRole"
            Principal:
              Service: "codebuild.amazonaws.com"
      Policies:
        - PolicyName: !Sub ${ApplicationName}-CodeBuild-${AWS::Region}
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Resource:
                  - "*"
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
              - Effect: Allow
                Resource:
                  - !Join
                    - ""
                    - - "arn:aws:s3:::"
                      - !Ref ArtifactBucket
                  - !Join
                    - ""
                    - - "arn:aws:s3:::"
                      - !Ref ArtifactBucket
                      - "/*"
                Action:
                  - "s3:DeleteObjectTagging"
                  - "s3:GetObjectRetention"
                  - "s3:DeleteObjectVersion"
                  - "s3:GetObjectVersionTagging"
                  - "s3:PutObjectVersionTagging"
                  - "s3:ListBucket"
                  - "s3:DeleteObjectVersionTagging"
                  - "s3:PutObjectLegalHold"
                  - "s3:GetObjectLegalHold"
                  - "s3:GetObjectVersionTorrent"
                  - "s3:PutObject"
                  - "s3:GetObjectAcl"
                  - "s3:GetObject"
                  - "s3:GetObjectTorrent"
                  - "s3:PutObjectRetention"
                  - "s3:GetObjectVersionAcl"
                  - "s3:GetObjectTagging"
                  - "s3:PutObjectTagging"
                  - "s3:GetObjectVersionForReplication"
                  - "s3:DeleteObject"
                  - "s3:GetObjectVersion"
              - Effect: Allow
                Resource:
                  - "*"
                Action:
                  - "cloudfront:CreateInvalidation"
              - Effect: "Allow"
                Action:
                  - "ssm:GetParameters"
                  - "ssm:GetParameter"
                Resource:
                  - "*"
  CodeBuild:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub ${ApplicationName}
      Description: !Sub Build project for ${ApplicationName}
      ServiceRole: !Ref CodeBuildRole
      Source:
        Type: CODEPIPELINE
        BuildSpec: infra/npm.buildspec.yml
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/nodejs:10.14.1
        Type: LINUX_CONTAINER
        EnvironmentVariables:
          - Name: NPM_TOKEN
            Value: '{{resolve:ssm:/SETTING/PROD/FRONTEND/AHA_UI_PUBLISH_NPM_TOKEN:1}}'
          - Name: NPM_TAG
            Value: !Ref NPMTag

      Artifacts:
        Name: !Ref ApplicationName
        Type: CODEPIPELINE
  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Sub ${ApplicationName}
      RoleArn: arn:aws:iam::551980366224:role/AWS-CodePipeline-Service
      ArtifactStore:
        Type: S3
        Location: !Ref ArtifactBucket
      Stages:
        - Name: Source
          Actions:
            - Name: Source
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Version: 1
                Provider: GitHub
              Configuration:
                Owner: !Ref GitHubOwner
                Repo: !Ref GitHubRepo
                Branch: !Ref GitHubBranch
                OAuthToken: '{{resolve:ssm:/SETTING/PROD/GOTIT_OPENSOURCE_GITHUB_TOKEN:1}}'
                PollForSourceChanges: true
              OutputArtifacts: [Name: Source]
              RunOrder: 1
        - Name: Build
          Actions:
            - Name: CodeBuild
              InputArtifacts: [Name: Source]
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              OutputArtifacts: [Name: Built]
              Configuration:
                ProjectName: !Ref CodeBuild
