name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - run: yarn install && cd aha-react && yarn install
      - run: npm run build
      - run: npm run deploy

